spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buddyfindr
    username: buddyfindr_user
    password: buddyfindr_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
  # Redis configuration
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  # Local development email configuration (using MailHog or disabled)
  mail:
    # If no email service is available, you can comment out the following configuration
    # host: localhost
    # port: 1025  # MailHog SMTP port
    # Or use Gmail configuration (requires app password)
    host: smtp.gmail.com
    port: 587
    username: example-email@gmail.com  # Replace with actual development email
    password: app-password     # Replace with Gmail app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: "furtrax_local_development_secret_key_2024_with_enough_length_for_hmac_sha256_algorithm"
  expiration: 86400000 # 1 day

# Server Configuration
server:
  port: 8080

# File Upload Configuration
file:
  upload-dir: ./uploads/

# Request Signature Configuration (can be disabled for local development)
signature:
  secret-key: "6haggb2ys1o216q7nojsptkzn1sasjtu"
  enabled: false  # Disable signature verification for local development

# SMS Configuration (using mock for local development)
aliyun:
  sms:
    access-key-id: "mock-access-key"
    access-key-secret: "mock-access-secret"
    sign-name: "FurTrax"
    template-code: "SMS_123456789"
    enabled: false  # Disable real SMS for local development

# Verification Code Configuration
verification:
  code:
    length: 6
    expiration: 300 # 5 minutes
    mock-enabled: true  # Enable mock verification codes for local development

# Third-party Login Configuration (using test configuration for local development)
third-party:
  facebook:
    app-id: "test-facebook-app-id"
    app-secret: "test-facebook-app-secret"
  google:
    client-id: "test-google-client-id"
    client-secret: "test-google-client-secret"

# Logging Configuration
logging:
  level:
    com.buddyfindr: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 